apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudz-fluentbit-parser
data:
  cloudz_parser.conf: |-
    [PARSER]
        Name        cloudz_parser
        Format      regex
        Regex       ^(?<logTime>\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}.\d{6}) (?<log>.*)$
        Time_Key    logTime
        Time_Format %Y/%m/%d %H:%M:%S.%L

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudz-fluentbit-config
data:
  fluent-bit.conf: |-
    [SERVICE]
        Parsers_File    /fluent-bit/etc/parsers.conf
        Parsers_File    /fluent-bit/etc/cloudz_parser.conf

    [INPUT]
        Name    tail
        Path    /mnt/podslog/${MY_POD_NAMESPACE}_${MY_POD_NAME}_*/cloudz/*.log
        Tag     cloudz
        Parser  cri
        Read_from_Head True
        Buffer_Max_Size 64k
        DB      cloudz.db

    [FILTER]
        Name      parser
        Match     cloudz
        Key_Name  message
        Parser    cloudz_parser

    [FILTER]
        Name    record_modifier
        Record  host ${MY_POD_NAME}
        Match   cloudz

    [OUTPUT]
        Name es
        Host elasticsearch
        Index cloudz
        HTTP_User elastic
        HTTP_Passwd parola
        Match *
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: main
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudz
  template:
    metadata:
      labels:
        app: cloudz
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
        prometheus.io/scheme: 'http'
    spec:
      containers:
      - name: cloudz
        image: cloudz:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
      - name: fluentbit-sidecar
        image: fluent/fluent-bit:1.8.8
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: podlogs
          mountPath: /mnt/podslog
          readOnly: true
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: fluentbit-parser
          mountPath: /fluent-bit/etc/cloudz_parser.conf
          subPath: cloudz_parser.conf
      volumes:
        - name: podlogs
          hostPath:
            path: /var/log/pods
        - name: fluentbit-config
          configMap:
            name: cloudz-fluentbit-config
        - name: fluentbit-parser
          configMap:
            name: cloudz-fluentbit-parser