apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config-cm
data:
  elasticsearch.yml: |
    network.host: 0.0.0.0
    discovery.seed_hosts: ["127.0.0.1", "[::1]"]
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elastic
  ports:
    - name: es-rest
      port: 9200
      targetPort: 9200
    - name: es-comms
      port: 9300
      targetPort: 9300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  labels:
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "true"
        - name: ELASTIC_PASSWORD
          value: "parola"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: elastic-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: elastic-config
        configMap:
          name: elastic-config-cm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.14.2
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "parola"
        - name: xpack.security.enabled
          value: "true"
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - name: main
      port: 5601
      targetPort: 5601
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudz-fluentbit-parser
data:
  cloudz_parser.conf: |-
    [PARSER]
        Name        cloudz_parser
        Format      regex
        Regex       ^(?<logTime>\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}.\d{6}) (?<log>.*)$
        Time_Key    logTime
        Time_Format %Y/%m/%d %H:%M:%S.%L

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudz-fluentbit-config
data:
  fluent-bit.conf: |-
    [SERVICE]
        Parsers_File    /fluent-bit/etc/parsers.conf
        Parsers_File    /fluent-bit/etc/cloudz_parser.conf

    [INPUT]
        Name    tail
        Path    /mnt/podslog/${MY_POD_NAMESPACE}_${MY_POD_NAME}_*/cloudz/*.log
        Tag     cloudz
        Parser  cri
        Read_from_Head True
        Buffer_Max_Size 64k
        DB      cloudz.db

    [FILTER]
        Name      parser
        Match     cloudz
        Key_Name  message
        Parser    cloudz_parser

    [FILTER]
        Name    record_modifier
        Record  host ${MY_POD_NAME}
        Match   cloudz

    [OUTPUT]
        Name es
        Host elasticsearch
        Index cloudz
        HTTP_User elastic
        HTTP_Passwd parola
        Match *
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: main
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudz
  template:
    metadata:
      labels:
        app: cloudz
    spec:
      containers:
      - name: cloudz
        image: cloudz:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
      - name: fluentbit-sidecar
        image: fluent/fluent-bit:1.8.8
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: podlogs
          mountPath: /mnt/podslog
          readOnly: true
        - name: fluentbit-config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: fluentbit-parser
          mountPath: /fluent-bit/etc/cloudz_parser.conf
          subPath: cloudz_parser.conf
      volumes:
        - name: podlogs
          hostPath:
            path: /var/log/pods
        - name: fluentbit-config
          configMap:
            name: cloudz-fluentbit-config
        - name: fluentbit-parser
          configMap:
            name: cloudz-fluentbit-parser